name: Deploy Plugin to Multiple Sites

on:
  push:
    branches:
      - main

jobs:
  deploy-lucca:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Deploy to Lucca
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.SITE1_FTP_HOST }}
        username: ${{ secrets.SITE1_FTP_USER }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./
        server-dir: ${{ secrets.SITE1_FTP_PATH }}
        exclude: |
          **/.git*
          **/.github/**
          **/node_modules/**
          **/composer.json
          **/README.md
        timeout: 120

  deploy-pistoia:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Deploy to Pistoia
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.SITE2_FTP_HOST }}
        username: ${{ secrets.SITE2_FTP_USER }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./
        server-dir: ${{ secrets.SITE2_FTP_PATH }}
        exclude: |
          **/.git*
          **/.github/**
          **/node_modules/**
          **/composer.json
          **/README.md
        timeout: 120

  deploy-lecce:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Deploy to Lecce
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.SITE3_FTP_HOST }}
        username: ${{ secrets.SITE3_FTP_USER }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./
        server-dir: ${{ secrets.SITE3_FTP_PATH }}
        exclude: |
          **/.git*
          **/.github/**
          **/node_modules/**
          **/composer.json
          **/README.md
        timeout: 120

  deploy-rieti:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Deploy to Rieti
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.SITE4_FTP_HOST }}
        username: ${{ secrets.SITE4_FTP_USER }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./
        server-dir: ${{ secrets.SITE4_FTP_PATH }}
        exclude: |
          **/.git*
          **/.github/**
          **/node_modules/**
          **/composer.json
          **/README.md
        timeout: 120

  deploy-aosta:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Deploy to Aosta
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.SITE5_FTP_HOST }}
        username: ${{ secrets.SITE5_FTP_USER }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./
        server-dir: ${{ secrets.SITE5_FTP_PATH }}
        exclude: |
          **/.git*
          **/.github/**
          **/node_modules/**
          **/composer.json
          **/README.md
        timeout: 120
