name: Deploy Plugin to Multiple Sites

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SITE1_USER: ${{ secrets.SITE1_FTP_USER }}
      SITE1_HOST: ${{ secrets.SITE1_FTP_HOST }}
      SITE1_PATH: ${{ secrets.SITE1_FTP_PATH }}
      SITE2_USER: ${{ secrets.SITE2_FTP_USER }}
      SITE2_HOST: ${{ secrets.SITE2_FTP_HOST }}
      SITE2_PATH: ${{ secrets.SITE2_FTP_PATH }}
      SITE3_USER: ${{ secrets.SITE3_FTP_USER }}
      SITE3_HOST: ${{ secrets.SITE3_FTP_HOST }}
      SITE3_PATH: ${{ secrets.SITE3_FTP_PATH }}
      SITE4_USER: ${{ secrets.SITE4_FTP_USER }}
      SITE4_HOST: ${{ secrets.SITE4_FTP_HOST }}
      SITE4_PATH: ${{ secrets.SITE4_FTP_PATH }}
      SITE5_USER: ${{ secrets.SITE5_FTP_USER }}
      SITE5_HOST: ${{ secrets.SITE5_FTP_HOST }}
      SITE5_PATH: ${{ secrets.SITE5_FTP_PATH }}
      FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}

    strategy:
      matrix:
        site:
          - { name: "Lucca", user: "${{ env.SITE1_USER }}", host: "${{ env.SITE1_HOST }}", path: "${{ env.SITE1_PATH }}" }
          - { name: "Pistoia", user: "${{ env.SITE2_USER }}", host: "${{ env.SITE2_HOST }}", path: "${{ env.SITE2_PATH }}" }
          - { name: "Lecce", user: "${{ env.SITE3_USER }}", host: "${{ env.SITE3_HOST }}", path: "${{ env.SITE3_PATH }}" }
          - { name: "Rieti", user: "${{ env.SITE4_USER }}", host: "${{ env.SITE4_HOST }}", path: "${{ env.SITE4_PATH }}" }
          - { name: "Aosta", user: "${{ env.SITE5_USER }}", host: "${{ env.SITE5_HOST }}", path: "${{ env.SITE5_PATH }}" }

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Deploy to ${{ matrix.site.name }}
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ matrix.site.host }}
        username: ${{ matrix.site.user }}
        password: ${{ env.FTP_PASSWORD }}
        local-dir: ./
        server-dir: ${{ matrix.site.path }}
        exclude: |
          **/.git*
          **/.github/**
          **/node_modules/**
          **/composer.json
          **/README.md
        timeout: 120
